export const ACCOUNTS = [
  ["ACC-001", "AED"],
  ["ACC-002", "BHD"],
];

export const EVENTS = Object.freeze([
  Object.freeze({
    id: "E1",
    day: 1,
    accountId: "ACC-001",
    type: "CREDIT",
    amount: "1200.00",
    valueDate: 1,
  }),
  Object.freeze({
    id: "E2",
    day: 1,
    accountId: "ACC-001",
    type: "DEBIT",
    amount: "950.00",
    valueDate: 1,
  }),
  Object.freeze({
    id: "E3",
    day: 2,
    accountId: "ACC-001",
    type: "AUTHORIZATION",
    amount: "200.00",
    valueDate: 2,
    authId: "Auth-A",
  }),
  Object.freeze({
    id: "E4",
    day: 3,
    accountId: "ACC-001",
    type: "CREDIT",
    amount: "400.00",
    valueDate: 3,
  }),
  Object.freeze({
    id: "E5",
    day: 4,
    accountId: "ACC-001",
    type: "SETTLEMENT",
    amount: "185.00",
    valueDate: 4,
    authId: "Auth-A",
  }),
  Object.freeze({
    id: "E6",
    day: 4,
    accountId: "ACC-001",
    type: "SETTLEMENT",
    amount: "180.00",
    valueDate: 4,
    authId: "Auth-Z",
  }),
  Object.freeze({
    id: "E7",
    day: 5,
    accountId: "ACC-001",
    type: "DEBIT",
    amount: "620.00",
    valueDate: 2,
  }),
  Object.freeze({
    id: "E8",
    day: 5,
    accountId: "ACC-001",
    type: "AUTHORIZATION",
    amount: "90.00",
    valueDate: 5,
    authId: "Auth-B",
  }),
  Object.freeze({
    id: "E9",
    day: 6,
    accountId: "ACC-001",
    type: "REVERSAL",
    valueDate: 2,
    reverses: "E7",
  }),
  Object.freeze({
    id: "E10",
    day: 5,
    accountId: "ACC-002",
    type: "CREDIT",
    amount: "10.000",
    valueDate: 5,
    instalments: 3,
  }),
]);
